### ISSUE TITLE
Support for Alpine Linux / APK

### ISSUE THREAD

**Issue by FireMasterK** [crowdsecurity/cs-nginx-bouncer#19]
Currently, I see a lot of dpkg related errors when running `./install.sh`, since Alpine Linux doesn't use dpkg!

**Comment by FireMasterK** [comment]
Any updates?

**Comment by LaurenceJJones** [comment]
Closing issue due to resolution being offered. Install.sh needs to support other OS's but alpine wont be included we officially support RPM, DEB
