### ISSUE TITLE
Need change log level

### ISSUE THREAD

**Issue by AsheK** [crowdsecurity/cs-nginx-bouncer#21]
Hi.

In this line need to change log level status on INFO (ngx.INFO).

https://github.com/crowdsecurity/cs-nginx-bouncer/blob/72fe89672f95de479b5d874d09b9df948601814e/nginx/crowdsec_nginx.conf#L9

**Comment by he2ss** [comment]
Hi @AsheK,

When we choose INFO level. With the default configuration it not appear in the error logs.
Maybe using NOTICE or ALERT level.
