### ISSUE TITLE
can't return 403

### ISSUE THREAD

**Issue by andyoulovexy** [crowdsecurity/cs-nginx-bouncer#40]
1、cscli decision add -i my accessip
2、when curl -I mysite ip，just pending,nothing retrun
![image](https://user-images.githubusercontent.com/38940994/199700888-befbb403-4481-4130-835e-b1dd4aeebe52.png)

**Comment by LaurenceJJones** [comment]
Are you running any other bouncers than nginx? as that is failing to connect so most likely firewall is dropping connection

**Comment by andyoulovexy** [comment]
> Are you running any other bouncers than nginx? as that is failing to connect so most likely firewall is dropping connection

nginx not work，swtich to openresty still not work

**Comment by andyoulovexy** [comment]
> > Are you running any other bouncers than nginx? as that is failing to connect so most likely firewall is dropping connection
> 
> nginx not work，swtich to openresty still not work

![image](https://user-images.githubusercontent.com/38940994/200213007-9c24bd18-a72a-41eb-aaba-6db44f4acafc.png)

**Comment by LaurenceJJones** [comment]
Yet you fail to answer the question can you please provide the output of `cscli bouncers list` please

**Comment by andyoulovexy** [comment]
> 啊，是的，这是你的问题，你有防火墙保镖，所以任何禁令都会被丢弃，在他们到达nginx或打开resty之前
> 
> 您需要为基于 http 的方案创建自定义禁止类型，或者插入自定义 iptables/nftables 规则以绕过我们的端口 80，443
> 
> 但简而言之，防火墙完全阻止了连接



> Ahhh yes that's your issue you have firewall bouncers so any bans will be dropped, before they can get to nginx or open resty
> 
> You either need to create a custom ban type for http based scenarios or insert custom iptables/nftables rules to bypass ours for port 80,443
> 
> But in short the firewall is blocking the connection entirely



> Ahhh yes that's your issue you have firewall bouncers so any bans will be dropped, before they can get to nginx or open resty
> 
> You either need to create a custom ban type for http based scenarios or insert custom iptables/nftables rules to bypass ours for port 80,443
> 
> But in short the firewall is blocking the connection entirely

Got it,i will try,thanks

**Comment by andyoulovexy** [comment]
> Ahhh yes that's your issue you have firewall bouncers so any bans will be dropped, before they can get to nginx or open resty
> 
> You either need to create a custom ban type for http based scenarios or insert custom iptables/nftables rules to bypass ours for port 80,443
> 
> But in short the firewall is blocking the connection entirely

Got it,i will try,thanks
