### ISSUE TITLE
Unable to locate package crowdsec-nginx-bouncer

### ISSUE THREAD

**Issue by earmstrong2020** [crowdsecurity/cs-nginx-bouncer#41]
I run the install command but unable to install it
Ubuntu 22.04 ARM64
Installed crowdsec_1.4.3_arm64.deb
nginx version: nginx/1.21.4

root@panel:~# sudo apt install crowdsec-nginx-bouncer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package crowdsec-nginx-bouncer

**Comment by LaurenceJJones** [comment]
See pinned issue about ubuntu 22.04 #38
