### ISSUE TITLE
Documentation needs to be updated to include other captcha methods

### ISSUE THREAD

**Issue by smac89** [crowdsecurity/cs-nginx-bouncer#43]
In the [docs](https://doc.crowdsec.net/docs/bouncers/nginx#setup-captcha), it says that only Google's recaptcha is supported, however the latest configuration file shows that in addition to recaptcha, `hcaptcha` and `turnstile` are also supported.

**Comment by LaurenceJJones** [comment]
Its has been added to `next`

https://doc.crowdsec.net/docs/next/bouncers/nginx#setup-captcha
