### ISSUE TITLE
Nginx bouncer showing unknown version after update

### ISSUE THREAD

**Issue by hhftechnology** [crowdsecurity/cs-nginx-bouncer#63]
![image](https://github.com/user-attachments/assets/55dfa628-e415-4f65-97b9-7dcc889163a8)

![image](https://github.com/user-attachments/assets/53819152-f8c9-41df-b190-374b26576dfc)

It has stopped generating alerts.

Everything else is working, I mean nginx, the sites and all other functions.

**Comment by LaurenceJJones** [comment]
> It has stopped generating alerts.

Bouncer are not in charge of generating alerts, that is the security engine itself.

Could you check that `/etc/nginx/conf.d/crowdsec.conf` exists and paste the contents in this issue if it does.

**Comment by serdimic** [comment]
I have the same issue. Installed just now  both `crowdsec` and `crowdsec-nginx-bouncer` on Ubuntu 24.04. Apparently no error, I just added recaptcha API key to configuration on default configuration and restart nginx and crowdsec services.
Output of `sudo cscli bouncers list` is:
![image](https://github.com/user-attachments/assets/af4ea258-1797-4921-b230-221587659c75)

The above mentioned file `/etc/nginx/conf.d/crowdsec.conf` does not exists, but the file `/etc/nginx/conf.d/crowdsec_nginx.conf` exists, and have this content:
```
lua_package_path '/usr/lib/crowdsec/lua/?.lua;;';
lua_shared_dict crowdsec_cache 50m;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
init_by_lua_block {
        cs = require "crowdsec"
        local ok, err = cs.init("/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf", "crowdsec-nginx-bouncer/v1.0.8")
        if ok == nil then
                ngx.log(ngx.ERR, "[Crowdsec] " .. err)
                error()
        end
        ngx.log(ngx.ALERT, "[Crowdsec] Initialisation done")
}

map $server_addr $unix {
        default       0;
        "~unix:" 1;
}

access_by_lua_block {
        local cs = require "crowdsec"
        if ngx.var.unix == "1" then
                ngx.log(ngx.DEBUG, "[Crowdsec] Unix socket request ignoring...")
        else
                cs.Allow(ngx.var.remote_addr)
        end
}
```
The nginx service logs seems to point out that crowdsec bouncer initialization is ok:
```
Dec 30 15:55:16 raspberrypi systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
Dec 30 15:55:17 raspberrypi nginx[240743]: nginx: [alert] [lua] crowdsec_nginx.conf:4):8: [Crowdsec] Initialisation done
Dec 30 15:55:17 raspberrypi systemd[1]: Started nginx.service - A high performance web server and a reverse proxy server.
```
and on crowdsec console I have:
![image](https://github.com/user-attachments/assets/9b31e587-d794-4844-bbb8-5d6b56f291a5)

**Comment by LaurenceJJones** [comment]
> I have the same issue. Installed just now both `crowdsec` and `crowdsec-nginx-bouncer` on Ubuntu 24.04. Apparently no error, I just added recaptcha API key to configuration on default configuration and restart nginx and crowdsec services. Output of `sudo cscli bouncers list` is: ![image](https://private-user-images.githubusercontent.com/123578532/399319483-af4ea258-1797-4921-b230-221587659c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzI2MTQsIm5iZiI6MTczNTU3MjMxNCwicGF0aCI6Ii8xMjM1Nzg1MzIvMzk5MzE5NDgzLWFmNGVhMjU4LTE3OTctNDkyMS1iMjMwLTIyMTU4NzY1OWM3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxNTI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTkzMGI2NjQzNzBjNGQ0NzU1ZmQ3ZDY3ZWMwYjg0OWQ4MWFlY2M0YTY2OGJmYmM0ZTI1ZWJmMGM5ZDgyNzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.A_4gYjxydny2Ph0a17bBrdrgJMntyHQubN3a70eN2co)
> 
> The above mentioned file `/etc/nginx/conf.d/crowdsec.conf` does not exists, but the file `/etc/nginx/conf.d/crowdsec_nginx.conf` exists, and have this content:
> 
> ```
> lua_package_path '/usr/lib/crowdsec/lua/?.lua;;';
> lua_shared_dict crowdsec_cache 50m;
> lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
> init_by_lua_block {
>         cs = require "crowdsec"
>         local ok, err = cs.init("/etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf", "crowdsec-nginx-bouncer/v1.0.8")
>         if ok == nil then
>                 ngx.log(ngx.ERR, "[Crowdsec] " .. err)
>                 error()
>         end
>         ngx.log(ngx.ALERT, "[Crowdsec] Initialisation done")
> }
> 
> map $server_addr $unix {
>         default       0;
>         "~unix:" 1;
> }
> 
> access_by_lua_block {
>         local cs = require "crowdsec"
>         if ngx.var.unix == "1" then
>                 ngx.log(ngx.DEBUG, "[Crowdsec] Unix socket request ignoring...")
>         else
>                 cs.Allow(ngx.var.remote_addr)
>         end
> }
> ```
> 
> The nginx service logs seems to point out that crowdsec bouncer initialization is ok:
> 
> ```
> Dec 30 15:55:16 raspberrypi systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
> Dec 30 15:55:17 raspberrypi nginx[240743]: nginx: [alert] [lua] crowdsec_nginx.conf:4):8: [Crowdsec] Initialisation done
> Dec 30 15:55:17 raspberrypi systemd[1]: Started nginx.service - A high performance web server and a reverse proxy server.
> ```
> 
> and on crowdsec console I have: ![image](https://private-user-images.githubusercontent.com/123578532/399320579-9b31e587-d794-4844-bbb8-5d6b56f291a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzI2MTQsIm5iZiI6MTczNTU3MjMxNCwicGF0aCI6Ii8xMjM1Nzg1MzIvMzk5MzIwNTc5LTliMzFlNTg3LWQ3OTQtNDg0NC1iYmI4LTVkNmI1NmYyOTFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQxNTI1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTRlYTA0YmI1OTNmOTBkNTQxNmY4NDJmYWZhYmQwZDg1YjhjOWUxODRiOTFiZWFkMWE5NGRlNGU3NWIyNWYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xRuHwykxMtaYNNoHFJr5SxI7KbnqRGgNUDPRtAwMbOM)

When the webserver gets a request, it should then reach out to LAPI. Can you send a request to your webserver and confirm you _still_ dont see anything?

**Comment by LaurenceJJones** [comment]
Yeah the nginx remediation only contacts `LAPI` once a single request has been processed, before that it kind of waits until then which can lead to this confusion. OP has not responded for some time so I will class as completed but if OP comes back with same issue please reopen 👍🏻

**Comment by bondskin** [comment]
Same here but all requests are being processed for days, still the Crowdsec web page says no metrics
swag          172.18.0.1  ✔️     2025-07-07T14:56:16Z  crowdsec-nginx-bouncer  v1.1.1   api-key

<img width="349" alt="Image" src="https://github.com/user-attachments/assets/c0191761-84d0-428a-a173-f5ae8196087d" />

**Comment by sabban** [comment]
From 1.1.1 version cs-nginx-bouncer, the /etc/nginx/conf.g/crowdsec_nginx.conf changed followed a significant change in the code in the way the code is initialized. I didn't find the swag Dockerfile around, so I couldn't check if this had been taken care of.
